# subtitle.py
import os
import pysrt
import webvtt
import xml.etree.ElementTree as ET

SUPPORTED_FORMATS = [
    "srt", "vtt", "ass", "ssa", "txt", "sub", "sbv", "mpl", "dfxp", "ttml"
]

def convert(input_path, output_path, fmt):
    fmt = fmt.lower()
    if fmt not in SUPPORTED_FORMATS:
        raise ValueError(f"Unsupported output format: {fmt}")

    input_ext = input_path.split(".")[-1].lower()
    if input_ext not in SUPPORTED_FORMATS:
        raise ValueError(f"Unsupported input format: {input_ext}")

    subtitles = parse_subtitle(input_path, input_ext)
    write_subtitle(subtitles, output_path, fmt)


def parse_subtitle(path, fmt):
    subtitles = []
    fmt = fmt.lower()
    if fmt == "srt":
        subs = pysrt.open(path, encoding="utf-8")
        for sub in subs:
            subtitles.append({"start": str(sub.start), "end": str(sub.end), "text": sub.text})
    elif fmt == "vtt":
        subs = webvtt.read(path)
        for sub in subs:
            subtitles.append({"start": sub.start, "end": sub.end, "text": sub.text})
    elif fmt in ["ass", "ssa"]:
        with open(path, "r", encoding="utf-8") as f:
            lines = f.readlines()
        for line in lines:
            if line.startswith("Dialogue:"):
                parts = line.split(",", 9)
                start = parts[1].strip()
                end = parts[2].strip()
                text = parts[9].strip()
                subtitles.append({"start": start, "end": end, "text": text})
    elif fmt == "txt":
        with open(path, "r", encoding="utf-8") as f:
            text = f.read()
        subtitles.append({"start": None, "end": None, "text": text})
    elif fmt in ["sub", "mpl", "sbv"]:
        with open(path, "r", encoding="utf-8") as f:
            lines = f.readlines()
        for line in lines:
            line = line.strip()
            if not line:
                continue
            if fmt == "sub":
                try:
                    start = line.split("}")[0].replace("{","")
                    end = line.split("}")[1].replace("{","")
                    text = "}".join(line.split("}")[2:])
                    subtitles.append({"start": start, "end": end, "text": text})
                except:
                    subtitles.append({"start": None, "end": None, "text": line})
            elif fmt == "mpl":
                try:
                    start = line.split("]")[0].replace("[","")
                    end = line.split("]")[1].replace("[","")
                    text = "]".join(line.split("]")[2:])
                    subtitles.append({"start": start, "end": end, "text": text})
                except:
                    subtitles.append({"start": None, "end": None, "text": line})
            elif fmt == "sbv":
                parts = line.split("\n")
                if len(parts) >= 2:
                    times = parts[0].split(",")
                    subtitles.append({"start": times[0], "end": times[1], "text": "\n".join(parts[1:])})
    elif fmt in ["dfxp", "ttml"]:
        tree = ET.parse(path)
        root = tree.getroot()
        ns = {'tt': 'http://www.w3.org/ns/ttml'}
        for p in root.findall('.//tt:p', ns):
            start = p.attrib.get('begin', None)
            end = p.attrib.get('end', None)
            text = "".join(p.itertext())
            subtitles.append({"start": start, "end": end, "text": text})
    else:
        raise ValueError(f"Unsupported input format: {fmt}")

    return subtitles


def write_subtitle(subtitles, path, fmt):
    fmt = fmt.lower()
    if fmt == "srt":
        subs_out = pysrt.SubRipFile()
        for i, sub in enumerate(subtitles, 1):
            if sub["start"] and sub["end"]:
                start = pysrt.SubRipTime.from_string(sub["start"])
                end = pysrt.SubRipTime.from_string(sub["end"])
            else:
                start = end = pysrt.SubRipTime(0,0,0,0)
            subs_out.append(pysrt.SubRipItem(index=i, start=start, end=end, text=sub["text"]))
        subs_out.save(path, encoding="utf-8")
    elif fmt == "vtt":
        vtt_out = webvtt.WebVTT()
        for sub in subtitles:
            start = sub["start"] if sub["start"] else "00:00:00.000"
            end = sub["end"] if sub["end"] else "00:00:00.000"
            vtt_out.captions.append(webvtt.Caption(start, end, sub["text"]))
        vtt_out.save(path)
    elif fmt in ["ass", "ssa"]:
        header = "[Script Info]\n; Generated by subtitle.py\n\n[V4+ Styles]\n\n[Events]\nFormat: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text"
        with open(path, "w", encoding="utf-8") as f:
            f.write(header + "\n")
            for sub in subtitles:
                start = sub["start"] if sub["start"] else "0:00:00.00"
                end = sub["end"] if sub["end"] else "0:00:00.00"
                f.write(f"Dialogue: 0,{start},{end},Default,,0,0,0,,{sub['text']}\n")
    elif fmt == "txt":
        with open(path, "w", encoding="utf-8") as f:
            for sub in subtitles:
                f.write(sub["text"] + "\n")
    elif fmt in ["sub", "mpl", "sbv"]:
        with open(path, "w", encoding="utf-8") as f:
            for sub in subtitles:
                start = sub["start"] if sub["start"] else ""
                end = sub["end"] if sub["end"] else ""
                text = sub["text"]
                if fmt == "sub":
                    f.write(f"{{{start}}}{{{end}}}{text}\n")
                elif fmt == "mpl":
                    f.write(f"[{start}][{end}]{text}\n")
                elif fmt == "sbv":
                    f.write(f"{start},{end}\n{text}\n")
    elif fmt in ["dfxp", "ttml"]:
        root = ET.Element("tt", xmlns="http://www.w3.org/ns/ttml")
        body = ET.SubElement(root, "body")
        div = ET.SubElement(body, "div")
        for sub in subtitles:
            p = ET.SubElement(div, "p")
            if sub["start"]:
                p.set("begin", sub["start"])
            if sub["end"]:
                p.set("end", sub["end"])
            p.text = sub["text"]
        tree = ET.ElementTree(root)
        tree.write(path, encoding="utf-8", xml_declaration=True)
